"""Persistence repositories export package."""

from persistence.repositories.artifact import (
    get_artifact_for_run_by_type,
    list_artifacts_for_run,
    list_uploaded_files_for_run,
    save_artifact_metadata,
    save_uploaded_file_metadata,
)
from persistence.repositories.audit import append_audit_event, list_audit_events
from persistence.repositories.base import RecordNotFoundError, RepositoryError, scoped_select
from persistence.repositories.certificate import (
    get_certificate_by_public_id,
    get_certificate_by_run_id,
    save_certificate,
)
from persistence.repositories.control_plane import (
    ControlPlaneError,
    create_membership,
    create_organisation,
    create_principal,
    get_active_membership,
    get_organisation,
    get_organisation_by_public_id,
    get_principal,
    get_principal_by_public_id,
    issue_tenant_context,
)
from persistence.repositories.cursor import decode_cursor, encode_cursor
from persistence.repositories.idempotency import (
    IdempotencyCollisionError,
    compute_request_hash,
    get_idempotency_record,
    save_idempotency_record,
)
from persistence.repositories.investigation import (
    list_investigations_by_run_id,
    save_investigations,
)
from persistence.repositories.job import (
    InvalidJobStateError,
    JobFencingError,
    cancel_ack_job,
    check_job_cancellation,
    claim_next_job,
    complete_job_fenced,
    create_reconciliation_job,
    fail_job,
    get_job_by_id,
    get_job_by_public_id,
    get_job_by_run_id,
    heartbeat_job,
    list_jobs,
    request_job_cancellation,
    revalidate_job_creator,
    transition_job_stage,
)
from persistence.repositories.result import (
    ResultIntegrityError,
    get_result_by_run_id,
    save_result,
)
from persistence.repositories.run import (
    InvalidRunStateError,
    RunUnderLegalHoldError,
    complete_run,
    create_run,
    fail_run,
    get_run_by_id,
    get_run_by_public_id,
    list_runs,
    list_runs_cursor,
    lock_run_for_update,
    set_run_legal_hold,
    soft_delete_run,
)

__all__ = [
    "ControlPlaneError",
    "IdempotencyCollisionError",
    "InvalidJobStateError",
    "InvalidRunStateError",
    "JobFencingError",
    "RecordNotFoundError",
    "RepositoryError",
    "ResultIntegrityError",
    "RunUnderLegalHoldError",
    "append_audit_event",
    "cancel_ack_job",
    "check_job_cancellation",
    "claim_next_job",
    "complete_job_fenced",
    "complete_run",
    "compute_request_hash",
    "create_membership",
    "create_organisation",
    "create_principal",
    "create_reconciliation_job",
    "create_run",
    "decode_cursor",
    "encode_cursor",
    "fail_job",
    "fail_run",
    "get_active_membership",
    "get_artifact_for_run_by_type",
    "get_certificate_by_public_id",
    "get_certificate_by_run_id",
    "get_idempotency_record",
    "get_job_by_id",
    "get_job_by_public_id",
    "get_job_by_run_id",
    "get_organisation",
    "get_organisation_by_public_id",
    "get_principal",
    "get_principal_by_public_id",
    "get_result_by_run_id",
    "get_run_by_id",
    "get_run_by_public_id",
    "heartbeat_job",
    "issue_tenant_context",
    "list_artifacts_for_run",
    "list_audit_events",
    "list_investigations_by_run_id",
    "list_jobs",
    "list_runs",
    "list_runs_cursor",
    "list_uploaded_files_for_run",
    "lock_run_for_update",
    "request_job_cancellation",
    "revalidate_job_creator",
    "save_artifact_metadata",
    "save_certificate",
    "save_idempotency_record",
    "save_investigations",
    "save_result",
    "save_uploaded_file_metadata",
    "scoped_select",
    "set_run_legal_hold",
    "soft_delete_run",
    "transition_job_stage",
]
