"""CI-safe stress and resource benchmark regression tests (Phase 1, Task 4).

Verifies:
1. End-to-end pipeline execution on CI-safe benchmark dataset.
2. All 7 mathematical and structural invariants under load:
   - Single terminal verdict per bank line
   - Complete attribution conservation (attributed + abstained == total)
   - Exact paise balance in all reconciled credits (within drift tolerance)
   - Double-entry balance in Tally/JSON journal vouchers (sum DR == sum CR)
   - Zero double-covered recon rows across credits
   - Cryptographic period close certificate validity
   - Deterministic execution (byte-identical audit root on rerun)
3. Safe abstention on ambiguous credits under load (no forced guessing).
4. Peak Python heap allocation bounds (< 25 MiB for CI-safe profile).
5. CLI entrypoint functionality (JSON output, solver flag, exit codes).
"""

from __future__ import annotations

import io
import json
import tracemalloc
from contextlib import redirect_stdout

import pytest

from eval.benchmark import main, run_benchmark
from eval.benchmark_generator import generate_benchmark_dataset


def test_ci_safe_benchmark_all_invariants_pass():
    """CI-safe benchmark profile runs and passes all 7 correctness invariants."""
    result = run_benchmark(profile="ci-safe", seed=42)

    assert result.invariants.all_passed is True, f"Invariant failures: {result.invariants.failures}"
    assert result.invariants.single_verdict_per_line is True
    assert result.invariants.attribution_conservation is True
    assert result.invariants.paise_conservation is True
    assert result.invariants.journal_balanced is True
    assert result.invariants.no_duplicate_covered_rows is True
    assert result.invariants.certificate_valid is True
    assert result.invariants.determinism_verified is True

    # Memory allocation bound (Python heap < 25 MiB for ~1.8k rows)
    assert result.peak_python_heap_bytes < 25 * 1024 * 1024

    # Output metrics sanity
    assert result.output_metrics["n_attributions"] > 0
    assert result.output_metrics["journal_vouchers_count"] > 0
    assert result.output_metrics["audit_root"] is not None


def test_benchmark_determinism_and_reproducibility():
    """Running the benchmark twice on identical generated bytes yields byte-identical audit roots."""
    ds = generate_benchmark_dataset(profile="ci-safe", seed=1337)
    res1 = run_benchmark(dataset=ds, seed=1337)
    res2 = run_benchmark(dataset=ds, seed=1337)

    assert res1.output_metrics["audit_root"] == res2.output_metrics["audit_root"]
    assert res1.output_metrics["reconciled_credits"] == res2.output_metrics["reconciled_credits"]
    assert res1.output_metrics["reconciled_paise"] == res2.output_metrics["reconciled_paise"]
    assert res1.output_metrics["exceptions_count"] == res2.output_metrics["exceptions_count"]


def test_benchmark_abstention_on_ambiguity():
    """Ambiguous credits in benchmark datasets must be abstained, never force-matched."""
    res = run_benchmark(profile="ci-safe", seed=42)
    assert res.output_metrics["unknown_count"] > 0
    assert res.output_metrics["by_rail_count"]["UNKNOWN"] == res.output_metrics["unknown_count"]


def test_benchmark_preserves_caller_tracemalloc_state():
    tracemalloc.start()
    try:
        run_benchmark(profile="ci-safe", seed=42)
        assert tracemalloc.is_tracing()
    finally:
        tracemalloc.stop()


def test_benchmark_nested_tracing_never_hides_historical_peak():
    tracemalloc.start()
    try:
        allocation = bytearray(2 * 1024 * 1024)
        del allocation
        historical_peak = tracemalloc.get_traced_memory()[1]
        result = run_benchmark(profile="ci-safe", seed=42)
        assert result.peak_python_heap_bytes >= historical_peak
    finally:
        tracemalloc.stop()


def test_benchmark_stops_owned_tracing_on_pipeline_error(monkeypatch):
    monkeypatch.setattr(
        "eval.benchmark.reconcile_bytes",
        lambda *args, **kwargs: (_ for _ in ()).throw(ValueError("boom")),
    )
    assert not tracemalloc.is_tracing()
    with pytest.raises(ValueError, match="boom"):
        run_benchmark(profile="ci-safe", seed=42)
    assert not tracemalloc.is_tracing()


def test_benchmark_cli_json_output():
    """`python -m eval.benchmark --json` prints machine-readable JSON and exits 0."""
    buf = io.StringIO()
    with redirect_stdout(buf):
        exit_code = main(["--profile", "ci-safe", "--seed", "42", "--json"])
    assert exit_code == 0
    output = buf.getvalue()
    parsed = json.loads(output)
    assert isinstance(parsed, dict)
    assert parsed["profile"] == "ci-safe"
    assert parsed["invariants"]["all_passed"] is True
    assert "peak_python_heap_mb" in parsed
    assert "duration_seconds" in parsed


def test_benchmark_cli_global_solver_mode():
    """`python -m eval.benchmark --global-solver` executes successfully with global solver enabled."""
    buf = io.StringIO()
    with redirect_stdout(buf):
        exit_code = main(["--profile", "ci-safe", "--seed", "42", "--global-solver"])
    assert exit_code == 0
    output = buf.getvalue()
    assert "Global Solver       : ENABLED (ON)" in output
    assert "OVERALL RESULT: [PASS]" in output
