#!/usr/bin/env python3
"""Fetch and self-host the exact Google Fonts weights the landing page uses.

Downloads latin + latin-ext woff2 subsets (CSP forbids external font hosts, so
everything is served from /static/fonts). Emits @font-face rules pointing at the
local files into tools/tailwind/fonts.css for inclusion in the Tailwind build.

Run from repo root:  python3 tools/tailwind/fetch_fonts.py
"""
from __future__ import annotations

import pathlib
import re
import sys
import urllib.request

CHROME_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

# (Google family name, css slug). All three are variable fonts, so one woff2 per
# subset covers every weight the landing page uses; we declare the full 100–900
# range on a single @font-face and let the browser pick the weight.
FAMILIES = [
    ("Hanken Grotesk", "hanken-grotesk"),
    ("Inter", "inter"),
    ("JetBrains Mono", "jetbrains-mono"),
]
# (Google family, css slug, weights used). Requesting the weight SET returns one
# variable woff2 per subset that spans the range (Google serves the same file for
# every weight in the request), so one file per subset covers all real weights.
FAMILY_WEIGHTS = {
    "Hanken Grotesk": [600, 700],
    "Inter": [400, 600, 700],
    "JetBrains Mono": [400, 500, 600],
}
KEEP_SUBSETS = {"latin", "latin-ext"}

ROOT = pathlib.Path(__file__).resolve().parents[2]
FONT_DIR = ROOT / "webapp" / "static" / "fonts"
OUT_CSS = ROOT / "tools" / "tailwind" / "fonts.css"

BLOCK_RE = re.compile(
    r"/\*\s*(?P<subset>[\w-]+)\s*\*/\s*(?P<block>@font-face\s*\{.*?\})",
    re.DOTALL,
)


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": CHROME_UA})
    with urllib.request.urlopen(req, timeout=30) as resp:  # noqa: S310 (trusted host)
        return resp.read()


def main() -> int:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    css_parts: list[str] = [
        "/* Self-hosted fonts — generated by tools/tailwind/fetch_fonts.py.",
        "   Do not edit by hand. Files live in webapp/static/fonts/. */",
    ]
    downloaded: list[str] = []

    for family, slug in FAMILIES:
        weights = FAMILY_WEIGHTS[family]
        wght = ";".join(str(w) for w in weights)
        weight_range = f"{min(weights)} {max(weights)}"
        css_url = (
            f"https://fonts.googleapis.com/css2?family="
            f"{family.replace(' ', '+')}:wght@{wght}&display=swap"
        )
        css = fetch(css_url).decode("utf-8")
        seen: set[str] = set()
        for m in BLOCK_RE.finditer(css):
            subset = m.group("subset")
            if subset not in KEEP_SUBSETS or subset in seen:
                continue
            seen.add(subset)
            block = m.group("block")
            range_m = re.search(r"unicode-range:\s*([^;]+);", block)
            url_m = re.search(r"src:\s*url\((https://[^)]+\.woff2)\)", block)
            if not url_m:
                continue
            fname = f"{slug}-{subset}.woff2"
            (FONT_DIR / fname).write_bytes(fetch(url_m.group(1)))
            downloaded.append(fname)
            unicode_range = range_m.group(1).strip() if range_m else ""
            face = "\n".join(
                [
                    "@font-face {",
                    f"  font-family: '{family}';",
                    "  font-style: normal;",
                    f"  font-weight: {weight_range};",
                    "  font-display: swap;",
                    f"  src: url('/static/fonts/{fname}') format('woff2');",
                    *([f"  unicode-range: {unicode_range};"] if unicode_range else []),
                    "}",
                ]
            )
            css_parts.append(face)

    # Fail loudly rather than commit an incomplete font set: a changed/partial
    # provider response must not silently replace the committed @font-face rules
    # (which would fall back to system fonts in production).
    expected = {
        f"{slug}-{subset}.woff2"
        for _family, slug in FAMILIES
        for subset in KEEP_SUBSETS
    }
    missing = expected - set(downloaded)
    if missing:
        raise SystemExit(
            f"incomplete font download: missing {sorted(missing)} "
            f"(got {sorted(downloaded)}). Refusing to write {OUT_CSS.name}."
        )

    OUT_CSS.write_text("\n\n".join(css_parts) + "\n", encoding="utf-8")
    print(f"downloaded {len(downloaded)} woff2 files to {FONT_DIR}")
    for f in sorted(downloaded):
        size = (FONT_DIR / f).stat().st_size
        print(f"  {f}  {size} bytes")
    print(f"wrote {OUT_CSS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
