/**
 * Tailwind config for the untangle upload page.
 * Mirrors the design tokens from the approved Stitch mockup. Dev-only: the CSS
 * it produces is compiled once and committed to webapp/static/landing.css, so
 * the running app never needs Node or a build step.
 */
module.exports = {
  darkMode: "class",
  content: [require("path").join(__dirname, "../../webapp/templates/upload.html")],
  theme: {
    extend: {
      colors: {
        "audit-blue": "#0f172a",
        "evidence-green": "#10B981",
        amber: "#F59E0B",
        "surface-container": "#e5eeff",
        "surface-bright": "#f8f9ff",
        "on-error": "#ffffff",
        "outline-variant": "#c6c6cd",
        "on-primary-fixed": "#131b2e",
        "tertiary-fixed-dim": "#ffb95f",
        background: "#f8f9ff",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#2a1700",
        "on-primary": "#ffffff",
        "on-secondary-container": "#00714d",
        "inverse-primary": "#bec6e0",
        tertiary: "#000000",
        surface: "#f8f9ff",
        "surface-tint": "#565e74",
        "on-background": "#0b1c30",
        "inverse-surface": "#213145",
        "on-tertiary-fixed-variant": "#653e00",
        "tertiary-fixed": "#ffddb8",
        "surface-container-highest": "#d3e4fe",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-fixed": "#002113",
        "on-surface-variant": "#45464d",
        "on-error-container": "#93000a",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed-variant": "#005236",
        "on-surface": "#0b1c30",
        "surface-container-low": "#eff4ff",
        "on-tertiary-fixed": "#2a1700",
        error: "#ba1a1a",
        outline: "#76777d",
        "secondary-container": "#6cf8bb",
        "surface-dim": "#cbdbf5",
        "surface-variant": "#d3e4fe",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-container": "#7c839b",
        "error-container": "#ffdad6",
        "secondary-fixed": "#6ffbbe",
        primary: "#000000",
        "primary-fixed-dim": "#bec6e0",
        secondary: "#006c49",
        "on-primary-fixed-variant": "#3f465c",
        "on-tertiary-container": "#b87500",
        "primary-fixed": "#dae2fd",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#131b2e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "row-height-standard": "48px",
        "container-padding": "24px",
        gutter: "16px",
        unit: "4px",
        "row-height-dense": "32px",
      },
      fontFamily: {
        "display-lg": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "label-caps": ["JetBrains Mono", "ui-monospace", "monospace"],
        "body-sm": ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "system-ui", "sans-serif"],
        "data-tabular": ["JetBrains Mono", "ui-monospace", "monospace"],
        "title-sm": ["Inter", "system-ui", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "data-tabular": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "title-sm": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
};
